apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dummy
spec:
  defaultBackend:
    service:
      name: dummy
      port:
        name: https
  ingressClassName: tailscale
  tls:
    - hosts:
        - dummy
