apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dummy
spec:
  defaultBackend:
    service:
      name: dummy
      port:
        number: 443
  ingressClassName: tailscale
  tls:
    - hosts:
        - dummy
