apiVersion: v1
kind: Service
metadata:
  name: dummy
  labels:
    app: dummy
spec:
  selector:
    app: dummy
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: https
  type: LoadBalancer
